package com.bomba.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.bomba.database.track;

import com.bomba.database.trackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;

    private final trackDao trackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(trackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        trackDao = new trackDao(trackDaoConfig, this);

        registerDao(track.class, trackDao);
    }
    
    public void clear() {
        trackDaoConfig.getIdentityScope().clear();
    }

    public trackDao getTrackDao() {
        return trackDao;
    }

}
